### ISSUE TITLE
Inquire stakeholders for requirements.

### ISSUE THREAD

**Issue by electr0de** [DefineX-Studios/MasjidBuddy#2]
Inquire with stakeholders :
Jama Masjid Ahle Hadees (Byculla W) : The trustees were generally receptive towards the following features:
1. Audio Streaming including darzs and azaan.
2. Namaz timings
3. Video Streaming.

They were positive above covering the hardware cost but might not be able to cover for the streaming cost.

Additional points to be noted: 
1. Regarding namaz timings, all the masjid in the enitre jamaat has the same timings. Hence once we know the timings of the jamaat we will know all the related masjid timings. We might even reduce their communication costs.
2. The trustee committee wants video streaming cost information.

**Comment by adsau59** [comment]
done
