### ISSUE TITLE
setup google auth

### ISSUE THREAD

**Issue by adsau59** [DefineX-Studios/MasjidBuddy#23]
- [x] setup client project
- [x] setup auth
  - [x] create component
  - [x] configure sign in button properly
  - [x] send token to supabase
  - [x] get new token and store
  - [x] figure out a way to keep secrets
  - [x] done

**Comment by electr0de** [comment]
https://vscode.dev/github/DefineX-Studios/MasjidBuddy/blob/main/code/presentation/mb-client/src/screens/login/index.tsx#L14-L17
Link for the code where you can call your API to put data for authentication

**Comment by adsau59** [comment]
look into https://starter.obytes.com/guides/authentication/

**Comment by adsau59** [comment]
configured google auth

was getting DEVELOPER_ERROR solved using [this solution](https://github.com/react-native-google-signin/google-signin/issues/1192#issuecomment-1670369305)

**Comment by adsau59** [comment]
also updated the documentation to have json file to ask for `secrets.json` file

![firefox_5jbVpzc01S](https://github.com/DefineX-Studios/MasjidBuddy/assets/10076396/285fd878-94da-4dcb-9f47-9f83da2714b1)

**Comment by adsau59** [comment]
tabs [setup google auth · Issue #23 · DefineX-Studios-MasjidBuddy  - 2023-12-07 22-00-41.json](https://github.com/DefineX-Studios/MasjidBuddy/files/13602648/setup.google.auth.Issue.23.DefineX-Studios-MasjidBuddy.-.2023-12-07.22-00-41.json)

**Comment by adsau59** [comment]
fixed, all done now

**Comment by adsau59** [comment]
done
