### ISSUE TITLE
cd .. && cd .. && cd .. && husky&nbsp;install

### ISSUE THREAD

**Issue by adsau59** [DefineX-Studios/MasjidBuddy#25]
this thing is pretty dirty

https://github.com/DefineX-Studios/MasjidBuddy/blob/main/code/presentation/mb-client/package.json#L26

instead of this, we should create a project root environment variable and then use that to refer everything instead

**Comment by electr0de** [comment]
Husky recommends on their official docs:
![image](https://github.com/DefineX-Studios/MasjidBuddy/assets/28353254/a2a0f3a5-d1a8-4b36-8fc3-c4ba88af3191)

**Comment by adsau59** [comment]
okay, closing the issue
