### ISSUE TITLE
Compile the evolving application requirements.

### ISSUE THREAD

**Issue by electr0de** [DefineX-Studios/MasjidBuddy#3]
Application requirements are present in the following document:
https://docs.google.com/document/d/17QqrIdzGIFjhba5MwfdCruKoQLLdaEHJGG6-YVs0sdI/edit?usp=sharing

**Comment by electr0de** [comment]
Hardware in Ahle Hadees Masjid to work with:
Masjid Audio Setup:

    Signature 12 eu mixing setup
    TZA 4000 EM - not in use
    Microgun 8300 drivecore install
    Yamaha mg06x

**Comment by adsau59** [comment]
done
