### ISSUE TITLE
create Hardware architecture.

### ISSUE THREAD

**Issue by electr0de** [DefineX-Studios/MasjidBuddy#7]
Architecture whiteboard:
 https://wbd.ms/share/v2/aHR0cHM6Ly93aGl0ZWJvYXJkLm1pY3Jvc29mdC5jb20vYXBpL3YxLjAvd2hpdGVib2FyZHMvcmVkZWVtLzM0NWMxNWUxOWM5MDQxODQ4MzFmM2IzMDg1NjFlNzc2X0JCQTcxNzYyLTEyRTAtNDJFMS1CMzI0LTVCMTMxRjQyNEUzRF82MzMwMDc4Zi1iMzQyLTQyNjQtYWQxYy05Y2RhNWQwMzVmZWQ=

**Comment by electr0de** [comment]
Based on the meeting the decision is made to follow the model 1.

**Comment by adsau59** [comment]
done
